---
title: "Testumgebung_App"
author: "Julian"
date: "2 6 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(dplyr)
library(tidyverse)
library(readr)
library(sf)
library(osmdata)
library(tmap)
library(eurostat)
library(plotly)
library(glue)
library(leaflet)
library(htmltools)
```

```{r}
df <- read_csv("data/schadstoffe-zeitreihen.csv")
geo_data <- read_rds("data/geo_schadstoffe.rds") %>%
  inner_join(df, by = "standort_id")  %>%
  select(c("standort_id", "geometry"))
geo_data <-geo_data[!duplicated(geo_data$standort_id), ] # considerably faster than distinct()
standorte <- as.vector(df[!duplicated(df$standort), "standort"])[['standort']] # make a list
vars <- as.data.frame(x = names(df)[4:8]) %>% rename("Schadstoff" = "names(df)[4:8]") # alle Variablen
vars <- vars[["Schadstoff"]]
```

```{r}


#calculate_valid_standorte <- function(){
  temp_df <- df
  for(i in standorte){
    ds <- typeof(i)
    x <- temp_df %>% 
      filter(standort == i) %>%
      select(kohlenmonoxid)%>%
      summarise(sum(!is.na(.))) 
    if(x == 0){
      temp_df <- temp_df %>%
        filter(standort != i)
      y <- "as"
    }
  }  
standorte_valid <- ((temp_df[!duplicated(temp_df$standort),"standort"][['standort']]))

#}

```

### Deutschlandkarte mit Bundeslandgrenzen
```{r}
sf <- eurostat::get_eurostat_geospatial(output_class = "sf", nuts_level = 1)
sf_germany <- sf %>% filter(CNTR_CODE=="DE") 
map_data <-geo_data %>%
  left_join(df)
map_data <- map_data[!duplicated(map_data$standort_id), c("gebiet", "standort", "hoehe", "typ")]

p <- sf_germany %>%
  ggplot() +
  geom_sf() +
  geom_sf(data = map_data, size = 2, mapping = aes(text = standort, color = typ))
ggplotly(p)
```
### leaflet
```{r}
map_data <- map_data %>%
  mutate(content = glue::glue(paste(sep = "<br/>",
  "<b><a>{standort}</a></b>",
  "Höhe: {hoehe}m",
  "Typ: {typ}")))

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(data = map_data$geometry, label = lapply(map_data$content, HTML)) 
m
```


### Plot the change of certain stations and variables

```{r}
vars = c("kohlenmonoxid", "stickstoffmonoxid")
station = "München/Landshuter Allee"
range = c("2020-01-01", "2021-01-01")

scale <- function(x, na.rm = FALSE) (x / first(x))

p <- df %>%
  filter(standort == station) %>%
  filter(datum >= range[1] & datum <= range[2]) %>%
  select(c(standort, datum, vars)) %>%
  mutate_at(vars, scale)%>%
  pivot_longer(cols = vars, names_to = "variables") %>%
  ggplot(aes(datum, value, color = variables)) +
  geom_line(size = 0.5) +
  labs(title = "")
  
plotly::ggplotly(p)
```

### Größten Verschmutzer je nach Zeitraum und Variable
```{r}
var = c("kohlenmonoxid")
range = c("2020-01-01", "2021-01-01")

df %>%
  select(c("datum", "standort", "hoehe", var)) %>%
  filter(standort  %in% standorte_valid) %>%
  group_by(standort) %>%
  summarise(mean = mean(!!sym(var), na.rm = TRUE)) %>%
  arrange(mean) %>%
  ggplot(aes(y = fct_reorder(standort, mean), x = mean)) +
  geom_bar(stat = "identity") +
  labs(title = glue::glue("Mittlerer Wert der {var}-Emissionen"),
       y = "Standort", x = "Mittlerer Wert der Konzentration")

```

